apiVersion: apps/v1
kind: Deployment
metadata:
  name: wavescreen-deployment
  namespace: wavescreen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wavescreen
  template:
    metadata:
      labels:
        app: wavescreen
    spec:
      containers:
      - name: wavescreen-frontend
        image: registry.germainleignel.com/personal/wavescreen-frontend:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: static-volume
          mountPath: /app/static
      volumes:
      - name: static-volume
        hostPath:
          path: /home/gmn/wavescreen/static
          type: DirectoryOrCreate
