apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-screenshots
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/gmn/wavescreen/screenshots
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-screenshots
  namespace: wavescreen
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi